version: '2'
services:
  equipos_ms:
    build: .
    command: python manage.py runserver 0.0.0.0:4002
    expose:
      - "4002"
    ports:
      - "4002:4002"
    volumes:
        - .:/code
    links:
    - equipos_db

  equipos_db:
    image: mongo
    volumes:
        - "mongodata:/data/db"
    ports:
      - "27017:27017"

volumes:
   mongodata: