version: '2'
services:
  teams-ms:
    build: .
    command: python manage.py runserver 0.0.0.0:4002
    expose:
      - "4002"
    ports:
      - "4002:4002"
    volumes:
        - .:/code
    links:
    - teams-db

  teams-db:
    image: mongo
    command: mongod --port 27020
    volumes:
        - "mongodata:/data/db"
    ports:
      - "27020:27020"

volumes:
   mongodata:
