version: '2'
services:
  teams_ms:
    build: .
    command: python manage.py runserver 0.0.0.0:4000
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
        - .:/code
    links:
    - teams_db

  teams_db:
    image: mongo
    volumes:
        - "mongodata:/data/db"
    ports:
      - "27017:27017"

volumes:
   mongodata: